name = "HDF5Arrays"
uuid = "c12d878e-345f-4eaf-97ca-0b55185efc42"
authors = ["Paul Nemec"]
version = "0.0.1"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
TiledIteration = "06e1c1a7-607b-532d-9fad-de7d9aa2abac"

[compat]
julia = "^1.3"
HDF5 = "^0.13"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
